# Generated by Django 2.2.13 on 2020-06-08 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200608_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('topic_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='article_images/')),
                ('description', models.CharField(max_length=10000)),
                ('article_type', models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], max_length=7)),
            ],
        ),
    ]
